---
consent:
  version: "1"
  author: Smart4Health
  id: s4h-consent-de
  lang: de
fonts:
  default: Helvetica
options:
  width: 8.75
  height: 8.75
  inputs:
    - page: 8
      "yes":
        x: 72.50
        y: 122.0
      "no":
        x: 72.50
        y: 98.0
    - page: 9
      "yes":
        x: 72.50
        y: 610.0
      "no":
        x: 72.50
        y: 585.0
    - page: 9
      "yes":
        x: 72.50
        y: 460.0
      "no":
        x: 72.50
        y: 435.0
    - page: 9
      "yes":
        x: 72.50
        y: 225.0
      "no":
        x: 72.50
        y: 200.0
signing:
  nameAndDate:
    fontSize: 16
    page: 9
    x: 330
    y: 152
    maxWidth: 236
    dateFormat: dd.MM.yyyy
  signature:
    page: 9
    x: 330
    y: 170
    maxWidth: 236
    maxHeight: 59
