---
consent:
  version: "1"
  author: Smart4Health
  id: s4h-consent-en
  lang: en
fonts:
  default: Helvetica
options:
  width: 12.25
  height: 12.25
  inputs:
    - page: 0
      "yes":
        x: 167.25
        y: 492.75
      "no":
        x: 393.75
        y: 492.75
    - page: 0
      "yes":
        x: 167.25
        y: 271.25
      "no":
        x: 393.75
        y: 271.25
    - page: 0
      "yes":
        x: 167.25
        y: 99.25
      "no":
        x: 393.75
        y: 99.25
    - page: 1
      "yes":
        x: 167.25
        y: 640
      "no":
        x: 393.75
        y: 640
    - page: 1
      "yes":
        x: 167.25
        y: 568.5
      "no":
        x: 393.75
        y: 568.5
signing:
  nameAndDate:
    fontSize: 20
    page: 1
    x: 74
    y: 90
    maxWidth: 500F
    dateFormat: dd.MM.yyyy
  signature:
    page: 1
    x: 74
    y: 120
    maxWidth: 500
    maxHeight: 50
